### ISSUE TITLE
EPIC: DEVICE UI CLASSES & FUNCTIONALITY

### ISSUE THREAD

**Issue by sofiecue** [ludigrizz/3004_Final_Project#18]
Complete Classes and Functionality for Device UI:

- [ ] LED class (rgb)
- [ ] Timers (new sess & countown 5min)
- [ ] date and time 
- [ ] MainWindow class
