### ISSUE TITLE
EPIC: Neureset Device

### ISSUE THREAD

**Issue by sofiecue** [ludigrizz/3004_Final_Project#23]
Functionality for the Device Main Page & Top Bar

### Top Bar
**Battery**
- [x] #26
Includes:
- [x] Enable charging for battery
- [x] Handle low Battery use case

**Power**
- [x] #24

**LED**
- [x] implement led lights
- [x] led lights blinking logic for session treatments? make the toggle functions for others to integrate later

### Date/Time Page
- [x] make confirm button save changes to date/time
- [x] test changes are effective in the logs page
- [x] Date/Time modal -> user device profile
- [x] make date/time dial usable

### New Session
- [x] [Create main timer (who's responsibility logic vs fed)](https://github.com/ludigrizz/3004_Final_Project/issues/16)
- [x] Make secondary timer if disconnected trigger occurs
- [x] Handle connection loss use cases
- [x] maek pause/start/stop buttons

### Session Logs
- [x] format text

### [PC UI](https://github.com/ludigrizz/3004_Final_Project/issues/13#issue-2209645657)
- [x] build log view -> what info is going in this text vs. device
- [x] how to get to this page 

### Afterthoughts
- [x] Improve details

### Diagrams Reflecting
- [x] State
- [x] UC
- [x] Traceability
